version: "3.1"
services:
    scheduler:
        volumes:
        - /Users/drewwhite/.creds/wdrew2-sa.json:/usr/local/airflow/gcloud/application_default_credentials.json:ro
    webserver:
        volumes:
        - /Users/drewwhite/.creds/wdrew2-sa.json:/usr/local/airflow/gcloud/application_default_credentials.json:ro
    triggerer:
        volumes:
        - /Users/drewwhite/.creds/wdrew2-sa.json:/usr/local/airflow/gcloud/application_default_credentials.json:ro